### ISSUE TITLE
Improve performance via using a window tiny LFU cache

### ISSUE THREAD

**Issue by LifeIsStrange** [ionic-team/stencil-store#117]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil-store/issues) that already include this feature request, without success.

### Describe the Feature Request

Stores caching of getters is [absolutely key for performance](https://github.com/vuejs/vuex/issues/2102) (hope you already cache them..)
However, while caching is important for performance, culturally, developers generally opt for a classic LRU cache, which is often signficiantly suboptimal.
The Java library Caffeine is the reference implementation of the state of the art caching algorithm [Window tiny LFU](https://github.com/ben-manes/caffeine/wiki/Efficiency#window-tinylfu), which is generally the best cache strategy.
There seems to exist a [straightforward JS](https://github.com/ahume/tiny-lfu-cache) port that you could leverage which would make stencil-store the first store out there to have a[ SOTA cache](https://github.com/ben-manes/caffeine/wiki/Efficiency#wikipedia).

### Describe Alternatives

1) no caching of getters hence subpar performance
2) caching but with a conventional LRU, AKA suboptimal performance for end users

### Related Code

https://github.com/ahume/tiny-lfu-cache

**Comment by alicewriteswrongs** [comment]
Interesting idea! We're always interested in ideas about how to improve Stencil and the Stencil ecosystem. I'm going to mark this as a feature request so we can get an idea of the community demand for it and look to prioritize work on it from there.

**Comment by Serabe** [comment]
I'm not following at all what @LifeIsStrange wants to do here. We don't have nor deal with _getters_ as in _computed properties_. Stencil Store is based on an observable map that basically creates a proxy around an object sending events whenever an access to a property is done. Stencil store does not provide computed properties or any value that needs to be cached directly AFAIK.

Can you please clarify where you want to use a cache in Stencil Store, please?

**Comment by LifeIsStrange** [comment]
@Serabe Sorry for the delay. Yes exactly my issue probably only apply to getters, which you currently do not support.
While my issue is of non-high priority (an optimization), bringing support for getters should be IMHO high priority:
it allows to perform:
* logging inside a getter
* allow devtools to log getters calls which massively help understand the flow of data
* validations (pre and post conditions checks)
* transformations including normalizations/sanitizations and business logic transforms, or even conditional accesses to other data sources, such as localstorage

getters is a basic feature found in many stores (Vuex, pinia, mobx, etc) and is critical for serious business uses.

**Comment by LifeIsStrange** [comment]
Well a store without observability, validations and transformations is not fit for real world use, that is a shame. Hope it wil be reconsidered.
