### ISSUE TITLE
Inferred types for `on` callback values

### ISSUE THREAD

**Issue by simonhaenisch** [ionic-team/stencil-store#18]
Example:

```ts
export const { state, on } = createStore({ foo: 'abc', bar: 123 });

on('set', (key, newValue, oldValue) => {
  if (key === 'foo') {
    // `newValue` and `oldValue` both have type `any`
  }
}
```

Wondering whether it would be possible to type it in a way that when I narrow down the key, it also narrows down the types of `newValue` and `oldValue`.

I might be able to look into this at some point... just leaving it here as a note that this would be neat.

**Edit:** Alternatively, it would be nice to expose `oldValue` in the `onChange` method (where it's easy to add type info for it). Then I wouldn't have a need for `on` anyway.

**Comment by Serabe** [comment]
We tres several approaches here but none seemed to work. If you fin anyway it would be great.

**Comment by manucorporat** [comment]
Doesn't seem typescript can do this, however, stencil/store has the `onChange` which listens for specific changes in props, and that one has strict types
