### ISSUE TITLE
Bump @stencil/core peerDependencies avoid warning

### ISSUE THREAD

**Issue by juliovedovatto** [ionic-team/stencil-store#25]
Since stencil is `v1.13.0`, it will be need to update `package.json` file to avoid peer dependency warning.

```
warning "my-package > @stencil/store@1.3.0" has unmet peer dependency "@stencil/core@>=1.10.0".
```

**Comment by Serabe** [comment]
I'm not seeing that problem when using `@stencil/core@1.13.0` with `@stencil/store@1.3.0`.

Can you paste your npm version (`npm -v`) and your `@stencil/x` versions (`cat package.json | grep @stencil`) here, please?

`@stencil/core@1.13.0` should be satisfying `@stencil/core>=1.10.0`.

Thank you!

**Comment by juliovedovatto** [comment]
Thanks for the quick feedback @Serabe 

We are using Stencil to build our UI components lib, while using Vue to deal with logic.

I'm getting this error when I install our stencil package as dependency, using `yarn`.

```
# cat package.json | grep @stenci
 "@stencil/core": "1.13.0",
 "@stencil/postcss": "^1.0.1",
 "@stencil/sass": "^1.3.1",
 "@stencil/store": "^1.3.0",
```

**Comment by Serabe** [comment]
It looks like the problem is that you added `@stencil/store` as `"dependencies"` and not as `"devDependencies"`.

If you are building a collection of components, `@stencil/store` needs to be added as a dev dependency as your distributed components will contain all the code already bundled in.

**Comment by juliovedovatto** [comment]
Yep, that was the cause @Serabe 

Please disregard this issue. It was a lack of attention on my part.

**Comment by Serabe** [comment]
No worries, happy to help!
