### ISSUE TITLE
Add CHANGELOG.md

### ISSUE THREAD

**Issue by fohlin** [ionic-team/stencil-store#26]
**Documentation request**. It would be great if this project started keeping a CHANGELOG file, documenting notable changes as development goes on. A `CHANGELOG.md` would conform nicely with [@ionic-team/stencil](https://github.com/ionic-team/stencil/blob/master/CHANGELOG.md) as well.

I think having a changlog in place for future releases will help Stencil Store users. I don't think there is any obligation to go back and document past changes. :-)

**Comment by rwaskiewicz** [comment]
Thanks for this suggestion @fohlin! Moving forward, we're going to use GitHub's changelog feature for [releases](https://github.com/ionic-team/stencil-store/releases) to keep track of what's changed in versions of this library. Thanks again!
