### ISSUE TITLE
Readme doesn't mention if state updates are async or not

### ISSUE THREAD

**Issue by Seanmclem** [ionic-team/stencil-store#28]
Readme doesn't mention if state updates are async or not, and the effects of that

**Comment by Serabe** [comment]
Hello, @Seanmclem!

The value of the property is changed synchronously and the component re-render is scheduled pretty much the same way it would when you change a local `@State()`.

Both changes end up calling [`scheduleUpdate`](https://github.com/ionic-team/stencil/blob/d91819ccf8a4d91af2e9a1a01bb5cbb7160a9236/src/runtime/update-component.ts#L17). `stencil-store` calls it via [`forceUpdate`](https://github.com/ionic-team/stencil/blob/d91819ccf8a4d91af2e9a1a01bb5cbb7160a9236/src/runtime/update-component.ts#L256) and changing a `@State()` calls it [here in `setValue`](https://github.com/ionic-team/stencil/blob/d91819ccf8a4d91af2e9a1a01bb5cbb7160a9236/src/runtime/set-value.ts#L78).

Not an expert on Stencil internals, so @manucorporat might correct me if I'm wrong.

Thank you!
