### ISSUE TITLE
Testing: Cannot read property '$hostElement$' of undefined

### ISSUE THREAD

**Issue by MartinJaskulla** [ionic-team/stencil-store#30]
- When testing components which use the store, I can only have a single test for them
- If I have more than one test, I am getting the error "TypeError: Cannot read property '$hostElement$' of undefined".
- Problem 1: When trying `beforeEach(() => store.reset())` as described in the [documentation](https://stenciljs.com/docs/stencil-store#testing).
- Problem 2: Without using/importing the store in my spec file at all, but testing a component with a method which interacts with the store. 

> For both problems you can comment out one of the tests to see the remaining one pass without any errors. As long as if there is only a single it() test, everything works as expected.
# Reproduce
- [Repo](https://github.com/MartinJaskulla/testing-with-store) with 2 branches. Branch "master" has the code for Problem 1. Branch "method" for problem 2.

Problem 1:
- `npm init stencil` and choose component starter
- Install devDependencies  @types/jest, jest, jest-cli, @types/puppeteer, puppeteer, @stencil/store
- Add store.ts
```typescript
import { createStore } from "@stencil/store";

export const store = createStore({
  clicks: 0
});
```
- Use in my-component.html
```typescript
export class MyComponent {
  render() {
    return <h1>{store.state.clicks}</h1>;
  }
}
```
- Change my.component.spec.ts
```typescript
describe('my-component', () => {
  beforeEach(() => {
    store.reset();
  });

  it('renders', async () => {
    const {root} = await newSpecPage({
      components: [MyComponent],
      html: '<my-component></my-component>'
    });
    expect(root).toEqualHtml(`
      <my-component>
        <mock:shadow-root>
          <h1>0</h1>
        </mock:shadow-root>
      </my-component>
    `);
  });
  it('renders', async () => {
    const {root} = await newSpecPage({
      components: [MyComponent],
      html: '<my-component></my-component>'
    });
    expect(root).toEqualHtml(`
      <my-component>
        <mock:shadow-root>
          <h1>0</h1>
        </mock:shadow-root>
      </my-component>
    `);
  });
});
```

 TypeError: Cannot read property '$hostElement$' of undefined

       5 | describe('my-component', () => {
       6 |   beforeEach(() => {
    >  7 |     store.reset();
         |           ^
       8 |   });

**Comment by Serabe** [comment]
Use `dispose` instead of `reset`

**Comment by MartinJaskulla** [comment]
That solves both problems. Thanks so much!
