### ISSUE TITLE
2_000, is it valid?

### ISSUE THREAD

**Issue by anonimusprogramus** [ionic-team/stencil-store#34]
I have no idea if it is actually valid, or typo.

https://github.com/ionic-team/stencil-store/blob/17019995f4d6db1c95757e799ef4120261f1c47d/src/subscriptions/stencil.ts#L21

**Comment by Serabe** [comment]
What do you mean?

**Comment by anonimusprogramus** [comment]
It's written `2_000`. Shouldn't it be `2000` (ms)?

**Comment by Serabe** [comment]
Yes, `2_000` is a valid number in JS. See [the numeric separator proposal already in stage 4](https://github.com/tc39/proposal-numeric-separator).

**Comment by anonimusprogramus** [comment]
I see, thank you!
