### ISSUE TITLE
Example usage of Subscriptions?

### ISSUE THREAD

**Issue by davidleger95** [ionic-team/stencil-store#35]
I noticed the `store.use()` method in the docs but I don't see any examples of how it's intended to be used. Could someone provide an example and context for when and how to use this method? Thanks!

**Comment by Serabe** [comment]
Subscriptions are simple ways to `use` (pun intended) several events at the same time. [I use a subscription in stencil-store-storage](https://github.com/Serabe/stencil-store-storage/blob/aee8fe0a9c1814dd9c0f3c1c485bddac38beeb48/src/stores/storage.ts#L52).

**Comment by akididou** [comment]
Yes a doc could be nice please !
