### ISSUE TITLE
Is this project actively maintained?

### ISSUE THREAD

**Issue by reins-ch** [ionic-team/stencil-store#42]
My PR #41 has not had any reviews or comments since I opened it 2 weeks ago.
Also some other PRs are still waiting for a longer time.

So now I am asking myself if I should use this package if it is not actively maintained (and still young).

**Comment by Serabe** [comment]
Yes. It is a small package and, as far as I know, considered feature complete at this point. Several projects I know use it in production and store keeps working with Stencil. I have a few projects (libraries and other) that depends on this too.

@manucorporat and I don't work on stencil full time, so this now depends on our works' schedules and personal lives (currently on holidays).

Next time, please, consider what your message might mean for people who is working on this for free and making this public for everyone to use. [Working in Public: The Making and Maintenance of Open Source Software](https://www.amazon.com/gp/product/B08BDGXVK9/ref=ppx_yo_dt_b_d_asin_title_o03?ie=UTF8&psc=1) is a great book you might want to read.
