### ISSUE TITLE
[Feature Request] computed state depending on multiple states

### ISSUE THREAD

**Issue by HarshRohila** [ionic-team/stencil-store#45]
readme example shows squared click example
```
onChange('clicks', value => {
  state.squaredClicks = value ** 2;
});
```
squared clicked computed from one state 'clicks'

to handle multiple dependent states I am doing like following
for speed depending on time and distance
```
onChange('distance', distance => {
  state.speed = distance / state.time;
});

onChange('time', time => {
  state.speed = state.distance / time;
});
```
while it works, a better api can be
```
onChange('distance', 'time', ([distance, time]) => {
   state.speed = distance / time;
})
```

**Comment by theo-staizen** [comment]
How about this?

```js
const updateSpeed = () => state.speed = state.distance / state.time;
['time', 'distance'].forEach(prop => onChange(prop, updateSpeed))
```

**Comment by HarshRohila** [comment]
> 
> 
> I'd vote against overloading the onChange method, just for that... How about doing this instead?
> 
> ```js
> const updateSpeed = () => state.speed = state.distance / state.time;
> const subscriptions = ['time', 'distance'].map(prop => onChange(prop, updateSpeed));
> ```
Nice, I wasn't expecting this to work, as I assumed state object may be having old state, and new state is supplied in callback(similar to react)
Now I wonder, why onChange api having state passed to callback, as its not required if we can read from state object itself

**Comment by Serabe** [comment]
> Now I wonder, why onChange api having state passed to callback, as its not required if we can read from state object itself

So you can share `onChange` callbacks.
