### ISSUE TITLE
does not reset the store to its initial state if empty array

### ISSUE THREAD

**Issue by peterpeterparker** [ionic-team/stencil-store#55]
The function `reset` does not seem to reset the store to its initial state if it was empty array.

Given a store such as 

```
interface MyStore {
  something: MyObject[];
}

const {state, reset} = createStore<MyStore>({
  something: []
});

export default {state, reset};
```

calling `myStore.reset()` has no effect on `something`.

**Comment by Serabe** [comment]
I cannot reproduce this issue. See https://github.com/Serabe/stencil-store-bug-55

Live demo is in https://wonderful-hopper-4b3af7.netlify.app/

The only thing that I can think is going wrong is that you are modifying the array in place somewhere. Try changing `MyStore` to:

```ts
interface MyStore {
  something: readonly MyObject[];
}
```

and see where TS tells you you are modifying the array in place.

**Comment by peterpeterparker** [comment]
Thanks for the feedback.

With your repo [stencil-store-bug-55](https://github.com/Serabe/stencil-store-bug-55) I can reproduce the issue if I `push` a value to the array in the store.

Indeed by destructuring the array as you did, there are no issues.

```
addRandom = () => {
    store.state.something = [...store.state.something, Math.random()];
  }
```

To the contrary, if you would `push` a value to the store, then `reset` has no effect.

```
addRandom = () => {
    store.state.something.push(Math.random());
  }
```

**Comment by Serabe** [comment]
If you do that, you are modifying the array in place meaning that the array you passed to `createStore` contains now an element. We hold a reference to that object and that object is now changed.

If you use `push` you don't only hit this, but the rerender system won't always work.

**Comment by peterpeterparker** [comment]
Yes, I know. Nevertheless would expect the `reset` function to reset the array contained in the store.

But if `push` is not supported, then I am fine, we can close the issue. Might worse to add a notice in the README about it though.

**Comment by peterpeterparker** [comment]
ps.: again thx for the feedback 👍
