### ISSUE TITLE
Nested store objects not being reset to it's initial state

### ISSUE THREAD

**Issue by perkrlsn** [ionic-team/stencil-store#66]
When using nested objects as part of your store, calling `store.reset()` will not reset the nested objects to their respective initial state values.

e.g.
```TypeScript
interface SomeStore {
  test1: {
    value: boolean;
  },
  test2: boolean;
}

const store = createStore<SomeStore>({
  test1: {
    value: false,
  },
  test2: false
});

```

**Comment by Serabe** [comment]
Same problem as this issue: https://github.com/ionic-team/stencil-store/issues/55

Will need to add some docs in the README about initial.

Other option is letting the user to provide a function that we would run to obtain the initial value, but that can open new problems as well.
